resume/urls.py
from django.urls import path

from resume.views import (
    CreateEducationView,
    CreateResumeSkillView,
    CreateWorkHistoryView,
    DeleteResumeAction,
    DeleteResumeEducationAction,
    DeleteResumeSocialAction,
    DeleteResumeWorkHistoryAction,
    DownloadResumeAction,
    ResumeDetailPDFView,
    ResumeDetailView,
    CreateResumeSocialsView,
    UpdateEducationView,
    UpdateResumeSkillView,
    UpdateResumeSocialsView,
    CreateResumeView,
    UpdateResumeView,
    ResumesView,
    UpdateWorkHistoryView,
    delete_skill,
    delete_skill_group,
)


app_name = "resume"

urlpatterns = [
    path(
        "create/",
        CreateResumeView.as_view(),
        name="create-resume-view",
    ),
    path(
        "edit/<int:resume_id>/",
        UpdateResumeView.as_view(),
        name="edit-resume-view",
    ),
    path(
        "create/socials/",
        CreateResumeSocialsView.as_view(),
        name="create-socials-view",
    ),
    path(
        "edit/socials/<int:resume_id>/",
        UpdateResumeSocialsView.as_view(),
        name="edit-socials-view",
    ),
    path(
        "<int:resume_id>/delete/socials/<int:social_id>/",
        DeleteResumeSocialAction.as_view(),
        name="delete-social",
    ),
    path(
        "create/education/",
        CreateEducationView.as_view(),
        name="create-education-view",
    ),
    path(
        "edit/education/<int:resume_id>/",
        UpdateEducationView.as_view(),
        name="edit-education-view",
    ),
    path(
        "<int:resume_id>/delete/education/<int:education_id>/",
        DeleteResumeEducationAction.as_view(),
        name="delete-education",
    ),
    path(
        "create/work-history/",
        CreateWorkHistoryView.as_view(),
        name="create-work-history-view",
    ),
    path(
        "edit/work-history/<int:resume_id>/",
        UpdateWorkHistoryView.as_view(),
        name="edit-work-history-view",
    ),
    path(
        "<int:resume_id>/delete/work-history/<int:work_history_id>/",
        DeleteResumeWorkHistoryAction.as_view(),
        name="delete-work-history",
    ),
    path(
        "create/skill/",
        CreateResumeSkillView.as_view(),
        name="create-skill-view",
    ),
    path(
        "edit/skill/<int:resume_id>/",
        UpdateResumeSkillView.as_view(),
        name="edit-skill-view",
    ),
    path(
        "delete/skill/<int:skill_id>/",
        delete_skill,
        name="delete-skill",
    ),
    path(
        "delete/skill-group/<int:group_id>/",
        delete_skill_group,
        name="delete-skill-group",
    ),
    path(
        "resumes/",
        ResumesView.as_view(),
        name="resumes-view",
    ),
    path(
        "<int:id>/view",
        ResumeDetailView.as_view(),
        name="resume-detail-view",
    ),
    path(
        "<int:id>/delete/",
        DeleteResumeAction.as_view(),
        name="delete-resume-action",
    ),
    path(
        "<int:id>/preview/",
        ResumeDetailPDFView.as_view(),
        name="preview-pdf-resume-view",
    ),
    path(
        "<int:id>/download/",
        DownloadResumeAction.as_view(),
        name="download-resume-action",
    ),
]

resumeproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from resumeproject.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("auth/", include("authentication.urls")),
    path("resume/", include("resume.urls")),
    path("", HomeView.as_view(), name="home-view"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user.views import (
    UserChangeEmailAction,
    UserChangePasswordAction,
    UserCreateView,
    UserDeleteAction,
    UserEditProfileView,
    UserProfileView,
    UserSettingsView,
)


app_name = "user"

urlpatterns = [
    path("create/", UserCreateView.as_view(), name="create-user-view"),
    path("profile/edit/", UserEditProfileView.as_view(), name="edit-profile-view"),
    path("profile/", UserProfileView.as_view(), name="profile-view"),
    path("settings/", UserSettingsView.as_view(), name="settings-view"),
    path(
        "settings/change-email",
        UserChangeEmailAction.as_view(),
        name="change-email-action",
    ),
    path(
        "settings/change-password",
        UserChangePasswordAction.as_view(),
        name="change-password-action",
    ),
    path("delete/", UserDeleteAction.as_view(), name="delete-user-action"),
]

resume/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from user.models import User


# Create your models here.
class Resume(models.Model):
    title = models.CharField(_("Title"), max_length=255)
    summary = models.TextField(_("Summary"), blank=True, null=True)
    first_name = models.CharField(_("First Name"), max_length=255)
    last_name = models.CharField(_("Last Name"), max_length=255)
    email = models.EmailField(_("Email Address"))
    phone = models.CharField(_("Phone Number"), max_length=15)
    image = models.ImageField(
        _("Resume Picture"),
        upload_to="images/resumes",
        blank=True,
        null=True,
        max_length=500,
    )
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    modified_at = models.DateTimeField(_("Modified At"), auto_now=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Social(models.Model):
    name = models.CharField(_("Name"), max_length=255)
    url = models.URLField(_("URL"))
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    modified_at = models.DateTimeField(_("Modified At"), auto_now=True)

    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)


class Education(models.Model):
    institution = models.CharField(_("Institution Name"), max_length=255)
    start_date = models.CharField(_("Start Date"), max_length=7)  # Format: MM/YYYY
    end_date = models.CharField(_("End Date"), max_length=7)  # Format: MM/YYYY
    degree = models.CharField(_("Degree"), max_length=255)

    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)


class WorkHistory(models.Model):
    name = models.CharField(_("Organization Name"), max_length=255)
    start_date = models.CharField(_("Start Date"), max_length=7)  # Format: MM/YYYY
    end_date = models.CharField(
        _("End Date"), max_length=7, blank=True, null=True
    )  # Optional
    position = models.CharField(_("Position"), max_length=255)
    description = models.TextField(_("Description"), blank=True, null=True)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    modified_at = models.DateTimeField(_("Modified At"), auto_now=True)

    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Work Histories"


class SkillGroup(models.Model):
    name = models.CharField(_("Skill Group Name"), max_length=255)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    modified_at = models.DateTimeField(_("Modified At"), auto_now=True)

    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, related_name="skill_groups")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["name", "resume"], name="unique_skillgroup_per_resume"
            )
        ]


class Skill(models.Model):
    name = models.CharField(_("Skill Name"), max_length=255)
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    modified_at = models.DateTimeField(_("Modified At"), auto_now=True)

    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    skill_group = models.ForeignKey(
        SkillGroup,
        on_delete=models.CASCADE,
        related_name="skills",  # Explicitly define the related_name
    )

resume/templates/resume/create-edit-resume-education.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="{% static 'css/resume/create-edit-resume-education.css' %}" rel="stylesheet">
{% endblock %}

{% block form %}
<form method="post"
    action="{% if action == 'Create' %} {% url 'resume:create-education-view' %}  {% else %} {% url 'resume:edit-education-view' resume_id=resume.id %} {% endif %}"
    class="form-create-edit-resume-education" enctype="multipart/form-data" data-resume-id="{{ resume.id }}">
    {% block formContent %}
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">{{ action }} Resume Educational Background</h1>

    {% if educations %}
    <div id="educationalBackground">
        {% for education in educations %}
        <div class="education-item">
            <input type="hidden" name="education-id" value="{{ education.id }}">
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingInstitutionName" placeholder="Institution Name"
                    name="institution" aria-required="true" value="{{ education.institution }}">
                <label for="floatingInstitutionName">Institution Name</label>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingStartDate" placeholder="MM/YYYY" name="start_date"
                    aria-required="true" pattern="(0[1-9]|1[0-2])/\d{4}" title="Format: MM/YYYY" value="{{ education.start_date }}">
                <label for="floatingStartDate">Start Date (MM/YYYY)</label>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingEndDate" placeholder="MM/YYYY" name="end_date"
                    aria-required="true" pattern="(0[1-9]|1[0-2])/\d{4}" title="Format: MM/YYYY" value="{{ education.end_date }}">
                <label for="floatingEndDate">End Date (MM/YYYY)</label>
            </div>

            <div class="form-floating">
                <input type="text" class="form-control" id="floatingDegree" placeholder="Degree" name="degree"
                    aria-required="true" value="{{ education.degree }}">
                <label for="floatingDegree">Degree</label>
            </div>
            <button class="btn btn-danger delete-education-button" id="deleteEducationItemButton" type="button">Delete
                #<span class="education-item-number">1</span></button>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div id="educationalBackground">
        <div class="education-item">
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingInstitutionName" placeholder="Institution Name"
                    name="institution" aria-required="true">
                <label for="floatingInstitutionName">Institution Name</label>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingStartDate" placeholder="MM/YYYY" name="start_date"
                    aria-required="true" pattern="(0[1-9]|1[0-2])/\d{4}" title="Format: MM/YYYY">
                <label for="floatingStartDate">Start Date (MM/YYYY)</label>
            </div>
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingEndDate" placeholder="MM/YYYY" name="end_date"
                    aria-required="true" pattern="(0[1-9]|1[0-2])/\d{4}" title="Format: MM/YYYY">
                <label for="floatingEndDate">End Date (MM/YYYY)</label>
            </div>

            <div class="form-floating">
                <input type="text" class="form-control" id="floatingDegree" placeholder="Degree" name="degree"
                    aria-required="true">
                <label for="floatingDegree">Degree</label>
            </div>
            <button class="btn btn-danger delete-education-button" id="deleteEducationItemButton" type="button">Delete
                #<span class="education-item-number">1</span></button>
        </div>
    </div>
    {% endif %}

    <p class="error-message">{{ error_message }}</p>

    <button class="btn btn-primary w-100 py-2 add-new-education-button" id="addNewEducationItemButton"
        type="button">Add</button>
    <button class="btn btn-primary w-100 py-2 submit-education-button" id="submitEducationButton"
        type="submit">Submit</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
    {% endblock %}
</form>

<script src="{% static 'js/resume/create-edit-resume-education.js' %}"></script>
{% endblock %}

resume/templates/resume/create-edit-resume-skill.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="{% static 'css/resume/create-edit-resume-skill.css' %}" rel="stylesheet">
{% endblock %}

{% block form %}
<form method="post"
    action="{% if action == 'Create' %} {% url 'resume:create-skill-view' %} {% else %} {% url 'resume:edit-skill-view' resume_id=resume.id %} {% endif %}"
    class="form-create-edit-resume-skills" enctype="multipart/form-data" data-resume-id="{{ resume.id }}">
    {% block formContent %}
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">{{ action }} Resume Skills</h1>

    <div id="skillGroupsContainer">
        {% if skill_groups %}
        {% for group in skill_groups %}
        <div class="skill-group-item" data-group-id="{{ group.id }}">
            <input type="hidden" name="skill-group-id" value="{{ group.id }}">

            <div class="form-floating">
                <input type="text" class="form-control" id="floatingSkillGroupName-{{ group.id }}"
                    placeholder="Skill Group Name" name="group_name" value="{{ group.name }}" aria-required="true">
                <label for="floatingSkillGroupName-{{ group.id }}">Skill Group Name</label>
            </div>

            <div id="skillsInGroup{{ group.id }}">
                {% for skill in group.skills.all %}
                <div class="skill-item" data-skill-id="{{ skill.id }}">
                    <input type="hidden" name="skill-id" value="{{ skill.id }}">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="floatingSkillName-{{ skill.id }}"
                            placeholder="Skill Name" name="skill_name" value="{{ skill.name }}" aria-required="true">
                        <label for="floatingSkillName-{{ skill.id }}">Skill Name</label>
                    </div>

                    {% if action == 'Edit' %}
                    <button class="btn btn-danger delete-skill-button" type="button">Delete Skill</button>
                    {% endif %}
                </div>
                {% endfor %}
            </div>

            <!-- Delete Skill Group Button -->
            <button class="btn btn-danger delete-skill-group-button" type="button">Delete Skill Group</button>

            <button class="btn btn-primary w-100 py-2 add-new-skill-button" data-group-id="{{ group.id }}"
                type="button">Add Skill to Group</button>
        </div>
        {% endfor %}
        {% else %}
        <div class="skill-group-item" data-group-id="0">
            <div class="form-floating">
                <input type="text" class="form-control" id="floatingSkillGroupName-0" placeholder="Skill Group Name"
                    name="group_name" aria-required="true">
                <label for="floatingSkillGroupName-0">Skill Group Name</label>
            </div>

            <div id="skillsInGroup0">
                <div class="skill-item" data-skill-id="0">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="floatingSkillName-0" placeholder="Skill Name"
                            name="skill_name" aria-required="true">
                        <label for="floatingSkillName-0">Skill Name</label>
                    </div>
                </div>
            </div>

            <button class="btn btn-primary w-100 py-2 add-new-skill-button" data-group-id="0" type="button">Add
                Skill</button>
            <!-- Delete Skill Group Button -->
            <button class="btn btn-danger delete-skill-group-button" type="button">Delete Skill Group</button>
        </div>
        {% endif %}
    </div>

    <button class="btn btn-primary w-100 py-2 submit-skill-button" type="submit">Submit</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
    {% endblock %}
</form>

<script src="{% static 'js/resume/create-edit-resume-skill.js' %}"></script>
{% endblock %}

resume/templates/resume/resume-detail-pdf.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @page {
            size: A4;
            margin: 0;
        }

        /* General Reset and A4 Page Setup */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Arial', 'Helvetica', sans-serif !important;
            background-color: #fff;
            margin: 0;
            padding: 1rem 0;
            height: 1123px;
            font-variant-ligatures: none;
        }

        .container {
            margin: 0 auto;
            max-width: 800px;
            padding: 0 1rem;
            height: 100%;
        }

        .resume-detail {
            width: 100%;
            padding: 1rem;
            margin: 0;
            font-size: 12px;
        }

        /* Centered Contact Info */
        .contact-details {
            text-align: center;
            margin-bottom: 20px;
        }

        .contact-details h2 {
            font-size: 22px;
            margin-bottom: 5px;
        }

        .contact-details h6 {
            font-size: 18px;
            margin-bottom: 10px;
        }

        .contact-details p {
            font-size: 14px;
            color: #555;
            margin: 5px 0;
        }

        .contact-details a {
            color: #007bff;
            text-decoration: none;
        }

        /* Resume Header and Profile Image */
        .resume-header {
            text-align: center;
            margin-bottom: 20px;
        }

        .resume-header img {
            width: 120px;
            height: 120px;
            border-radius: 50%;
            object-fit: cover;
        }

        /* Two-column layout for Resume Sections */
        .summary-section {
            margin-bottom: 20px;
        }

        .content-table {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            margin-top: 30px;
        }

        .content-table>div {
            width: 48%;
            margin-bottom: 20px;
        }

        .content-table h3 {
            font-size: 18px;
            color: #2c3e50;
            margin-bottom: 10px;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 5px;
        }

        .content-table ul {
            list-style: none;
            padding-left: 0;
        }

        .content-table li {
            margin-bottom: 15px;
        }

        .content-table .bold {
            font-weight: bold;
            color: #007bff;
        }

        .section-title {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        /* Skills Section */
        .skills-list {
            display: flex;
            flex-wrap: wrap;
            gap: 5px;
        }

        .skill-group {
            margin-bottom: 5px;
            padding: 5px;
            background-color: #f8f9fa;
            border-left: 5px solid #007bff;
            border-radius: 5px;
            width: 100%;
            box-sizing: border-box;
        }

        .skill-group-title {
            font-size: 1.2em;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
        }

        .skill-items {
            display: block;
            margin-top: 10px;
        }

        .skill-badge {
            display: inline-block;
            background-color: #007bff;
            color: white;
            padding: 5px 5px;
            border-radius: 15px;
            font-size: 0.9em;
            font-weight: bold;
            margin-right: 5px;
            margin-bottom: 5px;
        }

        /* .skills-list {
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
            align-items: center;
        } */

        /* .skill-badge {
            display: inline-block;
            background: #007bff;
            color: white;
            padding: 6px 12px;
            border-radius: 5px;
            font-size: 12px;
            white-space: nowrap;
            margin-bottom: 5px;
            margin-left: 5px;
        } */

        .work-history ul {
            list-style-type: disc;
            padding-left: 20px;
        }

        .work-history li {
            margin-bottom: 5px;
        }

        /* Conditional Download Link */
        .conditional-button {
            text-align: center;
            margin-top: 30px;
        }

        .download-button {
            position: fixed;
            bottom: 20px;
            right: 20px;
            background-color: #007bff;
            color: white;
            text-decoration: none;
            font-weight: bold;
            padding: 10px 20px;
            border-radius: 5px;
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
            transition: background 0.3s ease-in-out;
        }

        .download-button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="resume-detail">
            <!-- Profile Image -->
            <div class="resume-header">
                {% if resume.image %}
                <img src="{% if not is_preview %}{{ image_base64 }}{% else %}{{ resume.image.url }}{% endif %}"
                    alt="{{ resume.first_name }}'s Photo" />
                {% endif %}
            </div>

            <!-- Contact Details -->
            <div class="contact-details">
                <h2 class="owner-name">{{ resume.first_name }} {{ resume.last_name }}</h2>
                <h6>{{ resume.title }}</h6>
                <p>{{ resume.phone }} | <a href="mailto:{{ resume.email }}">{{ resume.email }}</a>
                    {% for social in resume.social_set.all %}
                    | <a href="{{ social.url }}">{{ social.url }}</a>
                    {% endfor %}
                </p>
            </div>

            <!-- Two Column Layout for Resume Content -->
            <div class="content-table">
                <!-- Left Column (Summary, Education, Work Experience) -->
                <div>
                    <div class="summary-section">
                        <h3 class="section-title">SUMMARY</h3>
                        <p>{{ resume.summary }}</p>
                    </div>

                    <h3 class="section-title">EDUCATION</h3>
                    <ul>
                        {% for education in resume.education_set.all %}
                        <li>
                            <p class="bold">{{ education.institution }}</p>
                            <p>{{ education.degree }}</p>
                            <p>{{ education.start_date }} - {{ education.end_date }}</p>
                        </li>
                        {% endfor %}
                    </ul>

                    <h3 class="section-title">WORK EXPERIENCE</h3>
                    <ul class="work-history">
                        {% for work_history in resume.workhistory_set.all %}
                        <li>
                            <p class="bold">{{ work_history.name }}</p>
                            <p><u>{{ work_history.position }}</u></p>
                            <p><u>{{ work_history.start_date }} -
                                    {% if work_history.end_date %}{{ work_history.end_date }}
                                    {% else %}Current{% endif %}
                                </u></p>
                            <ul>
                                {% for line in work_history.description.splitlines %}
                                <li class="description-item">{{ line }}</li>
                                {% endfor %}
                            </ul>
                        </li>
                        {% endfor %}
                    </ul>

                </div>

                <!-- Right Column -->
                <div>
                    <h3>Skills</h3>
                    <div class="skills-list">
                        <!-- Grouped Skills -->
                        {% for skill_group in skill_groups %}
                        <div class="skill-group">
                            <h4 class="skill-group-title">{{ skill_group.name }}</h4>
                            <div class="skill-items">
                                {% for skill in skill_group.skills.all %}
                                <span class="skill-badge">{{ skill.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        {% if is_preview == True %}
        <div class="conditional-button">
            <a href="{% url 'resume:download-resume-action' id=resume.id %}" target="_blank"
                class="download-button">Download Resume</a>
        </div>
        {% endif %}
    </div>
</body>

</html>

resume/templates/resume/resume-detail.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="{% static 'css/resume/resume.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="container">
        <div class="resume-detail">
            <!-- Profile Image -->
            <div class="resume-header">
                {% if resume.image %}
                <img src="{{ resume.image.url }}" alt="{{ resume.first_name }}'s Photo">
                {% endif %}
            </div>

            <!-- Contact Details -->
            <div class="contact-details">
                <h2 class="owner-name">{{ resume.first_name }} {{ resume.last_name }}</h2>
                <h6>{{ resume.title }}</h6>
                <p>{{ resume.phone }} | <a href="mailto:{{ resume.email }}">{{ resume.email }}</a>
                    {% for social in resume.social_set.all %}
                    | <a href="{{ social.url }}">{{ social.url }}</a>
                    {% endfor %}
                </p>
            </div>

            <!-- Two Column Layout -->
            <div class="content-table">
                <!-- Left Column -->
                <div>
                    <div class="summary-section">
                        <h3>Summary</h3>
                        <p>{{ resume.summary }}</p>
                    </div>

                    <h3>Work Experience</h3>
                    <ul>
                        {% for work_history in resume.workhistory_set.all %}
                        <li>
                            <p class="bold">{{ work_history.name }}</p>
                            <p>{{ work_history.position }}</p>
                            <p>{{ work_history.start_date }} - {% if work_history.end_date %}
                                {{ work_history.end_date }}{% else %}Current{% endif %}</p>
                            <p>{{ work_history.description|linebreaks }}</p>
                        </li>
                        {% endfor %}
                    </ul>

                    <h3>Education</h3>
                    <ul>
                        {% for education in resume.education_set.all %}
                        <li>
                            <p class="bold">{{ education.institution }}</p>
                            <p>{{ education.degree }}</p>
                            <p>{{ education.start_date }} - {{ education.end_date }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <!-- Right Column -->
                <div>
                    <h3>Skills</h3>
                    <div class="skills-list">
                        <!-- Grouped Skills -->
                        {% for skill_group in skill_groups %}
                        <div class="skill-group">
                            <h4 class="skill-group-title">{{ skill_group.name }}</h4>
                            <div class="skill-items">
                                {% for skill in skill_group.skills.all %}
                                <span class="skill-badge">{{ skill.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    {% if is_preview == True %}
    <div class="conditional-button">
        <a href="{% url 'resume:preview-pdf-resume-view' id=resume.id %}" target="_blank"
            class="download-button">Preview</a>
    </div>

</main>
<style>
    .conditional-button {
        position: fixed;
        bottom: 20px;
        left: 50%;
        transform: translateX(-50%);
        background-color: #007bff;
        padding: 10px 20px;
        border-radius: 5px;
        box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
    }

    .download-button {
        color: white;
        text-decoration: none;
        font-weight: bold;
    }
</style>
{% endif %}
</main>
{% endblock %}

resume/templates/resume/resumes.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="{% static 'css/resume/resumes.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="container">
        <div class="resumes-list">
            {% if user_resumes %}
            <ul class="resume-item">
                {% for resume in user_resumes %}
                <li>
                    <a class="resume-title" href="{% url 'resume:resume-detail-view' id=resume.id %}">
                        <p>{{ resume.title }}</p>
                    </a>
                    <div class="resume-actions">
                        <a href="{% url 'resume:delete-resume-action' id=resume.id %}" class="delete-button">Delete</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
</main>
{% endblock %}