authentication/urls.py
from django.urls import path

from authentication.views import (
    AuthLoginView,
    AuthLogoutView,
    AuthResetPasswordGetEmailView,
    AuthResetPasswordResetView,
    AuthResetPasswordSetTokenView,
)

app_name = "auth"

urlpatterns = [
    path("login/", AuthLoginView.as_view(), name="login-view"),
    path(
        "reset-password/email",
        AuthResetPasswordGetEmailView.as_view(),
        name="password-reset-get-email",
    ),
    path(
        "reset-password/token",
        AuthResetPasswordSetTokenView.as_view(),
        name="password-reset-set-token",
    ),
    path(
        "reset-password/password",
        AuthResetPasswordResetView.as_view(),
        name="password-reset",
    ),
    path("logout/", AuthLogoutView.as_view(), name="logout-view"),
]

resumeproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from resumeproject.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("auth/", include("authentication.urls")),
    path("resume/", include("resume.urls")),
    path("", HomeView.as_view(), name="home-view"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user.views import (
    UserChangeEmailAction,
    UserChangePasswordAction,
    UserCreateView,
    UserDeleteAction,
    UserEditProfileView,
    UserProfileView,
    UserSettingsView,
)


app_name = "user"

urlpatterns = [
    path("create/", UserCreateView.as_view(), name="create-user-view"),
    path("profile/edit/", UserEditProfileView.as_view(), name="edit-profile-view"),
    path("profile/", UserProfileView.as_view(), name="profile-view"),
    path("settings/", UserSettingsView.as_view(), name="settings-view"),
    path(
        "settings/change-email",
        UserChangeEmailAction.as_view(),
        name="change-email-action",
    ),
    path(
        "settings/change-password",
        UserChangePasswordAction.as_view(),
        name="change-password-action",
    ),
    path("delete/", UserDeleteAction.as_view(), name="delete-user-action"),
]

user/models.py
from random import choice

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import IntegrityError, models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from user.managers import UserManager


# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        _("Email address"),
        unique=True,
    )

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email


class Token(models.Model):
    token = models.CharField(
        _("Token"), blank=False, null=False, max_length=8, unique=True
    )
    token_expires = models.DateTimeField(
        _("Token Expires"), default=timezone.now() + timezone.timedelta(minutes=10)
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def generate(self) -> str:
        numbers = [str(i) for i in range(10)]
        token = ""

        for __ in range(8):
            token += choice(numbers)

        try:
            self.token = token
        except IntegrityError:
            token = self.generate()

        return token


class Profile(models.Model):
    first_name = models.CharField(_("First Name"), max_length=255)
    last_name = models.CharField(_("Last Name"), max_length=255)
    email = models.EmailField(_("Email Address"), unique=True)
    phone = models.CharField(_("Phone Number"), max_length=30, null=True)
    image = models.ImageField(
        _("Image"), upload_to="images/profiles", blank=True, null=True
    )
    created_at = models.DateTimeField(_("Created At"), auto_now_add=True)
    modified_at = models.DateTimeField(_("Modified At"), auto_now=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.email

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        return f"{self.first_name}"

user/views.py
from typing import Any

from django.http import HttpRequest, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from pydantic import validate_email
from pydantic_core import PydanticCustomError

from resumeproject.utils import email_error_message_handler
from user.models import Profile, User
from resumeproject.utils import ProtectedView


# Create your views here.
class UserCreateView(View):
    template = "user/register.html"
    title = "Register"
    context = {"title": title}

    def add_message(self, request, message, level=messages.INFO):
        messages.add_message(request, level, message)

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return render(request, self.template, self.context)

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        # Get form data from request.
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirm_password = request.POST.get("confirm_password")

        if email:

            # Handle user already exists.
            if User.objects.filter(email=email).exists():
                self.context.update(
                    {
                        "error_message": [
                            "Invalid input. This email address is already \
                    associated with an account."
                        ]
                    }
                )
                return render(request, self.template, self.context, status=409)

            # Handle password confirmation.
            if password == confirm_password:
                # Handle user creation.
                try:
                    User.objects.create_user(email, password)
                    # Pass message to template
                    self.add_message(
                        request,
                        "You have successfully created an account. Please login.",
                        messages.SUCCESS,
                    )
                    return redirect("auth:login-view")
                # Handle errors arising from user creation.
                # Handle errors of the type ValidationError.
                except ValidationError as e:
                    self.context.update({"error_message": list(e.messages)})
                    return render(request, self.template, self.context, status=400)
                # Handle errors of the type PydanticCustomError.
                except PydanticCustomError as e:
                    self.context.update(
                        {"error_message": email_error_message_handler(e.message())}
                    )
                    return render(request, self.template, self.context, status=400)
            else:
                self.context.update(
                    {
                        "error_message": ["Invalid input. Passwords do not match"],
                    }
                )
                return render(
                    request,
                    self.template,
                    self.context,
                    status=400,
                )
        self.context.update(
            {
                "error_message": ["Invalid input. No email provided."],
                }
            )
        return render(
            request,
            self.template,
            self.context,
            status=400,
        )


class UserEditProfileView(ProtectedView):
    template = "user/update-profile.html"
    page = "profile"
    title = "Edit Profile"
    context = {
        "page": page,
        "title": title,
    }
    next_page = "user:edit-profile-view"

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        try:
            # Get the profile for the authenticated user.
            user_profile = Profile.objects.get(user=request.user)
            # Update context to include the user's profile instance.
            self.context.update({"user_profile": user_profile})
            return render(request, self.template, self.context)
        except Profile.DoesNotExist:
            return render(request, self.template, self.context)

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        # Get form data from request.
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")

        # Handle image data.
        if "image" in request.FILES:
            image = request.FILES["image"]   
            import cloudinary.uploader
            cloudinary.uploader.upload(image, public_id=email)
        else:
            image = None

        try:
            # Get profile for the authenticated user.
            user_profile = Profile.objects.get(user=request.user)
            # Update values if profile is found.
            user_profile.first_name = first_name
            user_profile.last_name = last_name
            user_profile.email = email
            user_profile.phone = phone
            user_profile.image = image
        # Handle Profile not found exception.
        except Profile.DoesNotExist:
            import cloudinary.api
            # Create a new profile instance if one does not exist.
            user_profile = Profile.objects.create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone=phone,
                user=request.user,
                image=cloudinary.api.resource(email),
            )
        # Save the profile instance to the database.
        user_profile.save()
        # Redirect after the form is submitted.
        return redirect("user:profile-view")


class UserProfileView(ProtectedView):
    template = "user/profile.html"
    page = "profile"
    title = "Profile"
    context = {
        "page": page,
        "title": title,
    }
    next_page = "user:profile-view"

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        try:
            # Get the profile for the authenticated user.
            user_profile = Profile.objects.get(user=request.user)
        except Profile.DoesNotExist:
            # Redirect to edit-profile-view if profile does not exist.
            return redirect("user:edit-profile-view")

        # Update context to include the user's profile instance.
        self.context.update(
            {
                "user_profile": user_profile,
            }
        )
        return render(request, self.template, self.context)


class UserSettingsView(ProtectedView):
    template = "user/settings.html"
    page = "settings"
    title = "Settings"
    context = {
        "page": page,
        "title": title,
    }
    next_page = "user:settings-view"

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return render(request, self.template, self.context)


class UserDeleteAction(ProtectedView):
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        try:
            user = User.objects.get(id=request.user.id)
            user.delete()
            return redirect("home-view")
        except Exception:
            self.add_message(
                request, "An unexpected error has occurred.", messages.ERROR
            )
            return redirect("home-view")


class UserChangeEmailAction(ProtectedView):
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        new_email = request.POST.get("new_email")

        try:
            validate_email(new_email)
        except PydanticCustomError:
            return JsonResponse({"Error": "Invalid email address."}, status=400)
        if User.objects.filter(email=new_email).exists():
            return JsonResponse(
                {"Error": "An account is already associated with this email address."},
                status=400,
            )

        user = request.user
        user.email = new_email
        user.save()
        return JsonResponse(
            {"Message": "User email was successfully changed."}, status=200
        )


class UserChangePasswordAction(ProtectedView):
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> JsonResponse:
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        new_password_confirm = request.POST.get("new_password_confirm")

        user = request.user

        if new_password == new_password_confirm:
            try:
                if validate_password(new_password) is None:
                    if user.check_password(old_password):
                        user.set_password(new_password)
                        user.save()
                        return JsonResponse(
                            {"Message": "Password successfully changed."}, status=200
                        )
            except ValidationError as e:
                return JsonResponse({"Error": list(e.messages)}, status=400)
        else:
            return JsonResponse(
                {"Error": "Invalid input. Passwords do not match."}, status=400
            )

user/templates/user/password-change.html
{% extends 'dashboard.html' %}
{% load static %}

{% block form %}
<form method="post" class="form-change-password">
    {% block formContent %}
    {% csrf_token %}
    <img class="mb-4" src="{% static 'brand/bootstrap-logo.svg' %}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Change Password</h1>

    <div class="form-floating">
        <input type="password" class="form-control" id="floatingOldPassword" placeholder="Old Password"
            name="old_password" aria-required="true">
        <label for="floatingOldPassword">Old Password</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" id="floatingNewPassword" placeholder="New Password"
            name="new_password" aria-required="true">
        <label for="floatingNewPassword">New Password</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" id="floatingNewPasswordConfirm" placeholder="Confirm New Password"
            name="new_password_confirm" aria-required="true">
        <label for="floatingNewPasswordConfirm">Confirm New Password</label>
    </div>

    <button class="btn btn-primary w-100 py-2 update-profile-button" type="submit">Change Password</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
    {% endblock %}
</form>
{% endblock %}

user/templates/user/profile.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308801/assets/css/user/profile_dyhqz5.css"
    rel="stylesheet">
{% endblock %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="container">
        <div class="profile-card">
            <a href="{% if user_profile.image %}{{ user_profile.image.url }}{% endif %}">
                <img class="profile-image" src="{% if user_profile.image %}{{ user_profile.image.url }}{% endif %}"
                    alt="Profile Image">
            </a>
            <div class="profile-details">
                <h1 class="h3 mb-3 fw-normal">User Profile Details</h1>
                <p><strong>Name:</strong> {{ user_profile.first_name }} {{ user_profile.last_name }}</p>
                <p><strong>Email:</strong> {{ user_profile.email }}</p>
                <p><strong>Phone:</strong> {{ user_profile.phone }}</p>
                <a href="{% url 'user:edit-profile-view' %}" class="btn btn-primary">Edit Profile</a>
            </div>
        </div>
    </div>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
</main>
{% endblock %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block customStyle %}
<link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308802/assets/css/user/register_ogmvln.css"
    rel="stylesheet">
{% endblock %}

{% block formContent %}
{% csrf_token %}
<h1 class="h3 mb-3 fw-normal">Register</h1>

<div class="form-floating">
    <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="email"
        aria-required="true">
    <label for="floatingInput">Email address</label>
</div>
<div class="form-floating">
    <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="password"
        aria-required="true">
    <label for="floatingPassword">Password</label>
</div>
<div class="form-floating">
    <input type="password" class="form-control" id="floatingConfirmPassword" placeholder="Confirm Password"
        name="confirm_password" aria-required="true">
    <label for="floatingConfirmPassword">Confirm Password</label>
</div>

<p>Already have an account? <a href="{% url 'auth:login-view' %}">Log in</a></p>
<p>
<ul>
    {% if error_message %}
    {% for error in error_message %}
    <li class="error-list">
        {{ error }}
    </li>
    {% endfor %}
    {% endif %}
</ul>
</p>

<button class="btn btn-primary w-100 py-2" type="submit">Sign up</button>

<p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
{% endblock %}

user/templates/user/settings.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308802/assets/css/user/settings_h7u2a3.css"
    rel="stylesheet">
{% endblock %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="container">
        <h1 class="h3 mb-3 fw-normal">Account Settings</h1>
        <div class="profile-card">
            <div class="profile-details">
                <p><strong>Email:</strong>
                <p id="email">{{ user.email }}</p>
                </p>
                <div class="action-buttons">
                    <button id="changeEmailButton" class="btn btn-link">Change Email</button>
                    <button id="changePasswordButton" class="btn btn-link">Change Password</button>
                    <button id="deleteAccountModalButton" class="btn btn-link">Delete Account</button>
                </div>
                <div id="changeEmailForm" style="display: none;">
                    <form method="post" id="emailForm" class="form-update-email"
                        action="{% url 'user:change-email-action' %}">
                        {% csrf_token %}
                        <div class="form-floating">
                            <input type="email" class="form-control" id="floatingNewEmail" placeholder="New Email"
                                name="new_email" aria-required="true">
                            <label for="floatingNewEmail">New Email</label>
                        </div>
                        <button id="updateEmailButton" class="btn btn-primary w-100 py-2 update-email-button"
                            type="click">Change
                            Email</button>
                    </form>
                </div>

                <div id="changePasswordForm" style="display: none;">
                    <form method="post" id="passwordForm" class="form-update-password"
                        action="{% url 'user:change-password-action' %}">
                        {% csrf_token %}
                        <div class="form-floating">
                            <input type="password" class="form-control" id="floatingOldPassword"
                                placeholder="Old Password" name="old_password" aria-required="true">
                            <label for="floatingOldPassword">Old Password</label>
                        </div>
                        <div class="form-floating">
                            <input type="password" class="form-control" id="floatingNewPassword"
                                placeholder="New Password" name="new_password" aria-required="true">
                            <label for="floatingNewPassword">New Password</label>
                        </div>
                        <div class="form-floating">
                            <input type="password" class="form-control" id="floatingNewPasswordConfirm"
                                placeholder="Confirm New Password" name="new_password_confirm" aria-required="true">
                            <label for="floatingNewPasswordConfirm">Confirm New Password</label>
                        </div>
                        <button id="updatePasswordButton" class="btn btn-primary w-100 py-2 update-password-button"
                            type="click">Change
                            Password</button>
                    </form>
                </div>

                <div id="deleteAccountModal" class="modal" tabindex="-1" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Confirm Account Deletion</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete your account? This action cannot be undone.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <a href="{% url 'user:delete-user-action' %}" id="deleteAccountButton"
                                    class="btn btn-danger">Delete Account</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
</main>

<script src="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308811/assets/js/user/settings_sb6b0a.js"></script>
{% endblock %}

user/templates/user/update-profile.html
{% extends 'dashboard.html' %}
{% load static %}

{% block customStyle %}
<link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308803/assets/css/user/update-profile_ywdnbh.css"
    rel="stylesheet">
{% endblock %}

{% block form %}
<form method="post" class="form-update-profile" enctype="multipart/form-data">
    {% block formContent %}
    {% csrf_token %}

    <h1 class="h3 mb-3 fw-normal">Update Profile Details</h1>

    <div class="form-floating">
        <input type="text" class="form-control" id="floatingFirstName" placeholder="First Name" name="first_name"
            aria-required="true" value="{{ user_profile.first_name }}">
        <label for="floatingFirstName">First Name</label>
    </div>
    <div class="form-floating">
        <input type="text" class="form-control" id="floatingLastName" placeholder="Last Name" name="last_name"
            aria-required="true" value="{{ user_profile.last_name }}">
        <label for="floatingLastName">Last Name</label>
    </div>
    <div class="form-floating">
        <input type="email" class="form-control" id="floatingEmail" placeholder="name@example.com" name="email"
            aria-required="true" value="{{ user_profile.email }}">
        <label for="floatingEmail">Email address</label>
    </div>
    <div class="form-floating">
        <input type="tel" class="form-control" id="floatingPhone" placeholder="Phone Number" name="phone"
            aria-required="true" value="{{ user_profile.phone }}">
        <label for="floatingPhone">Phone Number</label>
    </div>
    <div class="form-floating">
        <input type="file" class="form-control" id="floatingImage" accept="image/*" name="image" aria-required="false"
            value="{{ user_profile.image }}">
        <label for="floatingImage">Profile Image</label>
    </div>

    <button class="btn btn-primary w-100 py-2 update-profile-button" type="submit">Update Profile</button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
    {% endblock %}
</form>
{% endblock %}