authentication/urls.py
from django.urls import path

from authentication.views import (
    AuthLoginView,
    AuthLogoutView,
    AuthResetPasswordGetEmailView,
    AuthResetPasswordResetView,
    AuthResetPasswordSetTokenView,
)

app_name = "auth"

urlpatterns = [
    path("login/", AuthLoginView.as_view(), name="login-view"),
    path(
        "reset-password/email",
        AuthResetPasswordGetEmailView.as_view(),
        name="password-reset-get-email",
    ),
    path(
        "reset-password/token",
        AuthResetPasswordSetTokenView.as_view(),
        name="password-reset-set-token",
    ),
    path(
        "reset-password/password",
        AuthResetPasswordResetView.as_view(),
        name="password-reset",
    ),
    path("logout/", AuthLogoutView.as_view(), name="logout-view"),
]

resume/urls.py
from django.urls import path

from resume.views import (
    CreateEducationView,
    CreateResumeSkillView,
    CreateWorkHistoryView,
    DeleteResumeAction,
    DeleteResumeEducationAction,
    DeleteResumeSocialAction,
    DeleteResumeWorkHistoryAction,
    DownloadResumeAction,
    ResumeDetailPDFView,
    ResumeDetailView,
    CreateResumeSocialsView,
    UpdateEducationView,
    UpdateResumeSkillView,
    UpdateResumeSocialsView,
    CreateResumeView,
    UpdateResumeView,
    ResumesView,
    UpdateWorkHistoryView,
    delete_skill,
    delete_skill_group,
)


app_name = "resume"

urlpatterns = [
    path(
        "create/",
        CreateResumeView.as_view(),
        name="create-resume-view",
    ),
    path(
        "edit/<int:resume_id>/",
        UpdateResumeView.as_view(),
        name="edit-resume-view",
    ),
    path(
        "create/socials/",
        CreateResumeSocialsView.as_view(),
        name="create-socials-view",
    ),
    path(
        "edit/socials/<int:resume_id>/",
        UpdateResumeSocialsView.as_view(),
        name="edit-socials-view",
    ),
    path(
        "<int:resume_id>/delete/socials/<int:social_id>/",
        DeleteResumeSocialAction.as_view(),
        name="delete-social",
    ),
    path(
        "create/education/",
        CreateEducationView.as_view(),
        name="create-education-view",
    ),
    path(
        "edit/education/<int:resume_id>/",
        UpdateEducationView.as_view(),
        name="edit-education-view",
    ),
    path(
        "<int:resume_id>/delete/education/<int:education_id>/",
        DeleteResumeEducationAction.as_view(),
        name="delete-education",
    ),
    path(
        "create/work-history/",
        CreateWorkHistoryView.as_view(),
        name="create-work-history-view",
    ),
    path(
        "edit/work-history/<int:resume_id>/",
        UpdateWorkHistoryView.as_view(),
        name="edit-work-history-view",
    ),
    path(
        "<int:resume_id>/delete/work-history/<int:work_history_id>/",
        DeleteResumeWorkHistoryAction.as_view(),
        name="delete-work-history",
    ),
    path(
        "create/skill/",
        CreateResumeSkillView.as_view(),
        name="create-skill-view",
    ),
    path(
        "edit/skill/<int:resume_id>/",
        UpdateResumeSkillView.as_view(),
        name="edit-skill-view",
    ),
    path(
        "delete/skill/<int:skill_id>/",
        delete_skill,
        name="delete-skill",
    ),
    path(
        "delete/skill-group/<int:group_id>/",
        delete_skill_group,
        name="delete-skill-group",
    ),
    path(
        "resumes/",
        ResumesView.as_view(),
        name="resumes-view",
    ),
    path(
        "<int:id>/view",
        ResumeDetailView.as_view(),
        name="resume-detail-view",
    ),
    path(
        "<int:id>/delete/",
        DeleteResumeAction.as_view(),
        name="delete-resume-action",
    ),
    path(
        "<int:id>/preview/",
        ResumeDetailPDFView.as_view(),
        name="preview-pdf-resume-view",
    ),
    path(
        "<int:id>/download/",
        DownloadResumeAction.as_view(),
        name="download-resume-action",
    ),
]

resumeproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from resumeproject.views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("auth/", include("authentication.urls")),
    path("resume/", include("resume.urls")),
    path("", HomeView.as_view(), name="home-view"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from user.views import (
    UserChangeEmailAction,
    UserChangePasswordAction,
    UserCreateView,
    UserDeleteAction,
    UserEditProfileView,
    UserProfileView,
    UserSettingsView,
)


app_name = "user"

urlpatterns = [
    path("create/", UserCreateView.as_view(), name="create-user-view"),
    path("profile/edit/", UserEditProfileView.as_view(), name="edit-profile-view"),
    path("profile/", UserProfileView.as_view(), name="profile-view"),
    path("settings/", UserSettingsView.as_view(), name="settings-view"),
    path(
        "settings/change-email",
        UserChangeEmailAction.as_view(),
        name="change-email-action",
    ),
    path(
        "settings/change-password",
        UserChangePasswordAction.as_view(),
        name="change-password-action",
    ),
    path("delete/", UserDeleteAction.as_view(), name="delete-user-action"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">

<head>
    <script src="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308808/assets/js/color-modes_o7cwby.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">

    <title>{{ title }}</title>

    <link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308807/assets/dist/js/bootstrap.min_aycjaw.js"
        rel="stylesheet">

    <link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308794/assets/css/base_niydvi.css"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block customStyle %}

    {% endblock %}
</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary">
    {% block themeChanger %}
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
            <path
                d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
            <path
                d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
            <path
                d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
            <path
                d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
        </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
        <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
            <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
                <use href="#circle-half"></use>
            </svg>
            <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                        <use href="#sun-fill"></use>
                    </svg>
                    Light
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                        <use href="#moon-stars-fill"></use>
                    </svg>
                    Dark
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                    <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                        <use href="#circle-half"></use>
                    </svg>
                    Auto
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
        </ul>
    </div>
    {% endblock %}

    {% block container %}
    <main class="form-signin w-100 m-auto">
        {% block content %}
        <form method="post" enctype="multipart/form-data">
            {% block formContent %}

            {% endblock %}
        </form>
        {% endblock %}
    </main>
    {% endblock %}

    <script
        src="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308807/assets/dist/js/bootstrap.min_aycjaw.js"></script>
    <script
        src="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308808/assets/dist/js/bootstrap.bundle.min_olg8h0.js"></script>

    {% block customScript %}
    {% endblock %}

</body>

</html>

templates/home.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">

<head>
  <script src="{% static 'js/color-modes.js' %}"></script>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.115.4">
  <title>Resume Builder</title>

  <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/home.css' %}" rel="stylesheet">

</head>

<body class="d-flex h-100 text-center theme-auto text-bg-auto">
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
      <path
        d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
      <path
        d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
      <path
        d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
      <path
        d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
    </symbol>
  </svg>

  <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
      aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
      <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
        <use href="#circle-half"></use>
      </svg>
      <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
          aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
            <use href="#sun-fill"></use>
          </svg>
          Light
          <svg class="bi ms-auto d-none" width="1em" height="1em">
            <use href="#check2"></use>
          </svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
          aria-pressed="false">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
            <use href="#moon-stars-fill"></use>
          </svg>
          Dark
          <svg class="bi ms-auto d-none" width="1em" height="1em">
            <use href="#check2"></use>
          </svg>
        </button>
      </li>
      <li>
        <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
          aria-pressed="true">
          <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
            <use href="#circle-half"></use>
          </svg>
          Auto
          <svg class="bi ms-auto d-none" width="1em" height="1em">
            <use href="#check2"></use>
          </svg>
        </button>
      </li>
    </ul>
  </div>


  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column theme-auto">
    <header class="mb-auto">
      <div>
        <h3 class="float-md-start mb-0">Resume Builder</h3>
      </div>
      <div>
        {% if user.is_authenticated %}
        <nav class="nav nav-masthead justify-content-center float-md-end gap-2">
          <a class="nav-link fw-bold py-1 px-0 theme-auto" href="{% url 'user:profile-view' %}">Dashboard</a>
          <form method="post" action="{% url 'auth:logout-view' %}">
            {% csrf_token %}
            <a>
              <button type="submit" class="nav-link fw-bold py-1 px-0 theme-auto">
                Logout
              </button>
            </a>
          </form>
        </nav>
        {% else %}
        <nav class="nav nav-masthead justify-content-center float-md-end">
          <a class="nav-link fw-bold py-1 px-0 theme-auto" href="{% url 'auth:login-view' %}">Login</a>
        </nav>
        {% endif %}
      </div>
    </header>

    <main class="px-3">
      {% if messages %}
      {% include 'messages.html' %}
      {% endif %}
      <h1>Resume Builder.</h1>
      {% if user.profile %}
      <p class="lead">Hello {{ user.profile.first_name }}, Build your resume using resume builder.</p>
      {% else %}
      <p class="lead">Build your resume using resume builder.</p>
      {% endif %}
      {% if user.is_authenticated %}
      <p class="lead">
        <a href="{% url 'resume:create-resume-view' %}"
          class="btn btn-lg theme-auto btn-auto fw-bold border-white bg-auto">Start
          building your Resume</a>
      </p>
      {% else %}
      <p class="lead">
        <a href="{% url 'user:create-user-view' %}"
          class="btn btn-lg theme-auto btn-auto fw-bold border-white bg-auto">Sign
          Up</a>
      </p>
      {% endif %}
    </main>

    <footer class="mt-auto text-white-50">
      <p>Resume builder by <a href="https://github.com/akinolaemmanuel49" target="_blank"
          class="text-white">@akinolaemmanuel49</a>.</p>
    </footer>
  </div>
  <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'dist/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

templates/messages.html
{% load static %}
{% block customStyle %}
<link href="https://res.cloudinary.com/dikkedkzf/raw/upload/v1695308796/assets/css/messages_ldomsg.css"
    rel="stylesheet">
{% endblock %}

<div id="messages-container">
    {% for message in messages %}
    <div class="alert alert-{{ message.level }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
</div>

templates/password_reset_email.html
<!DOCTYPE html>
<html>

<head>
    <title>Password Reset</title>
</head>

<body>
    <h2>Password Reset</h2>
    <p>Hello {% if user_profile %}{{ user_profile.first_name }}{% else %}User{% endif %},</p>
    <p>We received a request to reset the password for your account. If you didn't make this request, you can safely
        ignore this email.</p>
    <p>To reset your password, type in the reset token below into the reset token field:</p>
    <p>{{ token }}.</p>
    <p>This token will expire in 10 minutes.</p>
    <p>If you have any questions or need assistance, please contact our support team at support@example.com.</p>
    <p>Best regards,</p>
    <p>The ResumeBuilder Team</p>
</body>

</html>